// /brain API — the agent-facing read surface over the BRAIN shards.
//
// The static page (public/brain.html, generated by site/build_brain_page.py)
// fetches /assets/brain/* directly; these routes exist for AGENTS and remote
// tools that want one-call JSON without implementing the prefix-shard scheme:
//
//   GET /api/brain/node?id=<node id>     shard entry: {node, edges, breadcrumb,
//                                        children, rollup} + prov table
//   GET /api/brain/search?q=&type=&limit=  label search over labels.json
//
// Node ids per brain/SCHEMA.md: Q181296 | path:Mathlib/CategoryTheory |
// decl:Mathlib:CommGroup | lit:<arxiv>#<ref>. Ids carry ':'/'/' so they ride
// in a query param, not a path segment. The shard scheme is identical to the
// decl-index (build_shards.py mirrors build-decl-index.ts), so the resolver
// reuses declShardFor.
import type { Context, Hono } from "hono";
import type { Env } from "./env.js";
import { declShardFor } from "./decl.js";

// Interior spaces are legal (lit anchors like "lit:2110.15741#Theorem 2");
// only control chars and blank/overlong ids are rejected.
export const BRAIN_ID_RE = /^(?!\s*$)[^\p{C}]{1,400}$/u;
const ID_RE = BRAIN_ID_RE;

interface BrainManifest {
  scheme: { min_len: number; max_len: number; pad: string };
  shards: Record<string, number>;
  prov: Array<Record<string, string>>;
  roots: Array<Record<string, unknown>>;
  _meta: Record<string, unknown>;
}

async function assetJson<T>(c: Context<{ Bindings: Env }>, path: string): Promise<T | null> {
  const res = await c.env.ASSETS.fetch(new Request(new URL(path, c.req.url)));
  if (!res.ok) return null;
  return (await res.json()) as T;
}

// Resolve a node id to its shard entry (+ the manifest prov table), or null.
// Shared by GET /api/brain/node and the brain-edit write path (the shard set is
// the node-existence oracle — an edge endpoint must resolve to a real node).
export async function resolveBrainEntry(
  c: Context<{ Bindings: Env }>,
  id: string,
): Promise<{ entry: object; prov: Array<Record<string, string>> } | null> {
  const manifest = await assetJson<BrainManifest>(c, "/assets/brain/manifest.json");
  if (!manifest?.shards) return null;
  const key = declShardFor(
    { scheme: { min_len: manifest.scheme.min_len, max_len: manifest.scheme.max_len, pad: manifest.scheme.pad },
      shards: manifest.shards },
    id,
  );
  const shard = key
    ? await assetJson<Record<string, unknown>>(c, `/assets/brain/${key}.json`)
    : null;
  const entry = shard?.[id];
  if (!entry) return null;
  return { entry: entry as object, prov: manifest.prov };
}

// True iff `id` is a real brain node (used to validate edge endpoints).
export async function brainNodeExists(c: Context<{ Bindings: Env }>, id: string): Promise<boolean> {
  if (!BRAIN_ID_RE.test(id)) return false;
  return (await resolveBrainEntry(c, id)) !== null;
}

export function registerBrainRoutes(app: Hono<{ Bindings: Env }>): void {
  app.get("/api/brain/node", async (c) => {
    const id = c.req.query("id") || "";
    if (!ID_RE.test(id)) return c.json({ ok: false, error: "bad node id" }, 400);
    const resolved = await resolveBrainEntry(c, id);
    if (!resolved) return c.json({ ok: false, error: "unknown node id", id }, 404);
    return c.json(
      { ok: true, id, ...resolved.entry, prov_table: resolved.prov },
      200,
      // shards change only on nightly data rebuilds
      { "Cache-Control": "public, max-age=3600" },
    );
  });

  app.get("/api/brain/search", async (c) => {
    const q = (c.req.query("q") || "").trim().toLowerCase();
    if (q.length < 2) return c.json({ ok: false, error: "query too short (min 2 chars)" }, 400);
    const type = c.req.query("type") || "";
    const limit = Math.min(Number(c.req.query("limit")) || 25, 100);
    const labels = await assetJson<Array<{ id: string; type: string; label: string }>>(
      c, "/assets/brain/labels.json");
    if (!labels) return c.json({ ok: false, error: "brain data unavailable" }, 503);
    // a bare QID query matches an existing node by id (so a concept is findable
    // by "Q181296", not only its label)
    const isQid = /^q[1-9][0-9]{0,11}$/.test(q);
    const starts: object[] = [], contains: object[] = [];
    for (const r of labels) {
      if (type && r.type !== type) continue;
      const l = r.label.toLowerCase();
      if (l.startsWith(q) || (isQid && r.id.toLowerCase() === q)) starts.push(r);
      else if (l.includes(q)) contains.push(r);
      if (starts.length >= limit) break;
    }
    return c.json(
      { ok: true, q, hits: [...starts, ...contains].slice(0, limit) },
      200,
      { "Cache-Control": "public, max-age=3600" },
    );
  });
}
