// AUTO-GENERATED from wikifunctions/data/wikifunctions_specs_verified.jsonl.
// Do not hand-edit; regenerate if the verified corpus changes. The corpus
// is small (25 rows) and never changes per-request, so it is embedded rather
// than queried — this page is fully self-contained (no D1, no migrations).

export type Tier = "composite_provable" | "oracle_testable" | "spec_only";
export type Faithfulness = "faithful" | "wrong_target" | "representation_mismatch";
export type Computable = "decidable" | "computable_nat_int" | "float" | "noncomputable_real";

export interface WfFunction {
  zid: string;
  qid: string;
  name: string;
  oracleDecl: string;
  /** Bare Mathlib decl name for the docs deep-link, or "" when the oracle is a composite expression. */
  docDecl: string;
  computable: Computable;
  faithfulness: Faithfulness;
  faithfulnessNote: string;
  tier: Tier;
}

export const WF_FUNCTIONS: readonly WfFunction[] = [
  {
    zid: "Z12427",
    qid: "Q49008",
    name: "is prime",
    oracleDecl: "decide (Nat.Prime n)  -- via instance Nat.decidablePrime",
    docDecl: "Nat.Prime",
    computable: "decidable",
    faithfulness: "faithful",
    faithfulnessNote: "Nat.Prime : ℕ → Prop is exactly the primality predicate on naturals; the WF signature (Natural number) -> Boolean matches via the Decidable instance Nat.decidablePrime, so decide (Nat.Prime n) returns the Bool the WF returns. Mathlib itself tags this def with @[wikidata Q49008] — the exact QID in this task — confirming the concept match. No string/float encoding, no typeclass target.",
    tier: "composite_provable",
  },
  {
    zid: "Z13521",
    qid: "Q32043",
    name: "add",
    oracleDecl: "Nat.add (equivalently the `(· + ·)` / HAdd.hAdd on ℕ)",
    docDecl: "Nat.add",
    computable: "computable_nat_int",
    faithfulness: "wrong_target",
    faithfulnessNote: "primary_decl \"AddCommMonoid\" is a typeclass (the abstract additive-commutative-monoid STRUCTURE), confirmed verbatim as `class AddCommMonoid` at Mathlib/Algebra/Group/Defs.lean:788. It is not the addition operation. The Wikifunction computes a + b on natural numbers; the actual oracle is Nat.add (Lean core), which the `AddCommMonoid ℕ` instance is literally built from (`add := Nat.add` in instAddCancelCommMonoid at Mathlib/Algebra/Group/Nat/Defs.lean:30, with the AddCommMonoid ℕ instance derived at line 71). The (ℕ,ℕ)->ℕ signature itself is faithful to ℕ→ℕ→ℕ; only the chosen decl is mis-targeted at the typeclass instead of the operation.",
    tier: "composite_provable",
  },
  {
    zid: "Z13612",
    qid: "Q131752",
    name: "greatest common divisor",
    oracleDecl: "Nat.gcd",
    docDecl: "Nat.gcd",
    computable: "computable_nat_int",
    faithfulness: "wrong_target",
    faithfulnessNote: "primary_decl `GCDMonoid` exists verbatim as `class GCDMonoid` (Mathlib/Algebra/GCDMonoid/Basic.lean:246), but it is a TYPECLASS abstracting gcd/lcm over a CommMonoidWithZero — it does not compute a value for concrete ℕ inputs. The WF signature (ℕ,ℕ)→ℕ is conceptually correct gcd, so the faithful computable oracle is `Nat.gcd : ℕ → ℕ → ℕ`. The `GCDMonoid ℕ` instance literally sets `gcd := Nat.gcd`, and `gcd_eq_nat_gcd m n : gcd m n = Nat.gcd m n := rfl` (Mathlib/Algebra/GCDMonoid/Nat.lean:43) ties the typeclass operation to the concrete computable def. Secondary decls: GCDMonoid.gcd is the abstract projection (noncomputable in general); EuclideanDomain.gcd, Int.gcd_eq_gcd_ab, Finset.gcd are tangential / different domains.",
    tier: "composite_provable",
  },
  {
    zid: "Z13660",
    qid: "Q102761",
    name: "least common multiple",
    oracleDecl: "Nat.lcm",
    docDecl: "Nat.lcm",
    computable: "computable_nat_int",
    faithfulness: "wrong_target",
    faithfulnessNote: "primary_decl `GCDMonoid` exists verbatim at Mathlib/Algebra/GCDMonoid/Basic.lean:246, but it is a typeclass (`class GCDMonoid (α) [CommMonoidWithZero α] extends IsCancelMulZero α`) whose `lcm : α → α → α` field is abstract and not computable on a concrete type. The Wikifunction signature is (ℕ, ℕ) → ℕ, so the faithful, computable oracle is the concrete `Nat.lcm` (Lean core), defined as `Nat.lcm m n = m * n / Nat.gcd m n`. Note `GCDMonoid.lcm` instantiated at ℕ would NOT directly defeq `Nat.lcm`: ℕ uses a NormalizedGCDMonoid instance routed through `Nat.gcd`/`Nat.lcm`, but the typeclass projection is the wrong handle for an oracle. The concept (LCM of two naturals) is correctly identified; only the decl target (typeclass vs operation) is wrong.",
    tier: "composite_provable",
  },
  {
    zid: "Z13667",
    qid: "Q120976",
    name: "factorial",
    oracleDecl: "Nat.factorial",
    docDecl: "Nat.factorial",
    computable: "computable_nat_int",
    faithfulness: "faithful",
    faithfulnessNote: "Wikifunction sig is (Natural number) -> Natural number, exactly matching Nat.factorial : ℕ → ℕ. The primary_decl is the actual operation (a recursive def), not a typeclass, and not a string/float encoding. Defined as 0! = 1, (n+1)! = (n+1) * n!. The decl already carries @[wikidata Q120976], matching the QID.",
    tier: "composite_provable",
  },
  {
    zid: "Z13701",
    qid: "Q104752",
    name: "are coprime",
    oracleDecl: "Nat.Coprime (i.e. decide (Nat.Coprime m n)); definitionally Nat.gcd m n = 1",
    docDecl: "Nat.Coprime",
    computable: "decidable",
    faithfulness: "faithful",
    faithfulnessNote: "WF signature (ℕ, ℕ) -> Bool exactly matches \"are m and n coprime\" = decide (Nat.Coprime m n). primary_decl IsCoprime EXISTS verbatim (Mathlib/RingTheory/Coprime/Basic.lean:45, and it does carry @[wikidata Q104752]), but it is the Bezout-style predicate ∃ a b, a*x+b*y=1 over a CommSemiring — a Prop with no general Decidable instance, and its own docstring warns it is \"not a straightforward generalization of Nat.Coprime.\" So IsCoprime is the right CONCEPT for the ring-theoretic notion but the WRONG oracle for a computable Boolean over ℕ. The computable ground truth is the core def Nat.Coprime (= gcd = 1, [reducible], decidable). For naturals the two agree via Nat.isCoprime_iff_coprime (over ℤ). Concept is faithful; only the chosen decl needed swapping for the decidable one.",
    tier: "composite_provable",
  },
  {
    zid: "Z13822",
    qid: "Q2741788",
    name: "modular inverse",
    oracleDecl: "fun (a n : ℕ) => ((a : ZMod n)⁻¹).val   -- ⁻¹ is ZMod.inv; .val is the canonical residue",
    docDecl: "ZMod.inv",
    computable: "computable_nat_int",
    faithfulness: "faithful",
    faithfulnessNote: "ZMod.inv (Mathlib.Data.ZMod.Basic:711) exists verbatim inside `namespace ZMod`: `def inv : ∀ n : ℕ, ZMod n → ZMod n | 0, i => Int.sign i | n+1, i => Nat.gcdA i.val (n+1)`. It is the genuine modular multiplicative inverse, computed via the extended Euclidean algorithm (Nat.gcdA / Nat.xgcd, computable). Its native type is ZMod n → ZMod n, not the WF's (ℕ,ℕ)→ℕ; the correspondence to the WF signature is (a,n) ↦ ((a : ZMod n)⁻¹).val, where .val gives the canonical 0≤r<n representative. Correctness precondition is coprimality: ZMod.mul_inv_eq_gcd gives a*a⁻¹ = gcd a.val n, so a*a⁻¹ = 1 iff Coprime a n (ZMod.coe_mul_inv_eq_one, ZMod.mul_val_inv). Concept and domain match the Wikidata notion, so faithful (only a thin cast/.val wrapper differs).",
    tier: "composite_provable",
  },
  {
    zid: "Z13835",
    qid: "Q23835349",
    name: "nth Fibonacci number",
    oracleDecl: "Nat.fib",
    docDecl: "Nat.fib",
    computable: "computable_nat_int",
    faithfulness: "faithful",
    faithfulnessNote: "Wikifunction signature (Natural number) -> Natural number maps exactly to Nat.fib : ℕ → ℕ. Nat.fib is the concrete computable arithmetic function (not a typeclass), defined via Function.iterate with convention fib 0 = 0, fib 1 = 1 (OEIS A000045), characterized by Nat.fib_add_two: fib (n+2) = fib n + fib (n+1). primary_decl is correct.",
    tier: "composite_provable",
  },
  {
    zid: "Z13955",
    qid: "Q190026",
    name: "Euler totient",
    oracleDecl: "Nat.totient",
    docDecl: "Nat.totient",
    computable: "computable_nat_int",
    faithfulness: "faithful",
    faithfulnessNote: "primary_decl Nat.totient is the actual operation (a `def`, not a typeclass), encoded over ℕ exactly matching the WF signature (Natural number) -> (Natural number). Defined as `#{a ∈ range n | n.Coprime a}` = count of naturals < n coprime to n, the standard Euler totient. Convention φ(0)=0, φ(1)=1 matches Wikidata Q190026.",
    tier: "composite_provable",
  },
  {
    zid: "Z14933",
    qid: "Q170043",
    name: "is perfect number",
    oracleDecl: "decide (Nat.Perfect n)",
    docDecl: "Nat.Perfect",
    computable: "decidable",
    faithfulness: "faithful",
    faithfulnessNote: "WF signature \"(Natural number) -> Boolean\" matches Nat.Perfect : ℕ → Prop exactly via `decide`. Nat.Perfect n is defined as `∑ i ∈ properDivisors n, i = n ∧ 0 < n` (Divisors.lean:399), the standard definition of a perfect number (sum of proper divisors equals n, positivity excludes 0). properDivisors is a concrete computable Finset ℕ, so the Prop is decidable via the default And/Eq ℕ/LT ℕ instances — no bespoke Decidable instance is declared but one is synthesized automatically. Not a typeclass/structure and not a string/float encoding.",
    tier: "composite_provable",
  },
  {
    zid: "Z15483",
    qid: "Q331350",
    name: "nth r-simplex number",
    oracleDecl: "Nat.choose (n + r - 1) r  -- equivalently Nat.multichoose n r (Nat.multichoose_eq)",
    docDecl: "Nat.multichoose",
    computable: "computable_nat_int",
    faithfulness: "wrong_target",
    faithfulnessNote: "primary_decl Affine.Simplex is a geometric `structure Simplex (n : ℕ)` (a collection of n+1 affinely independent points in an affine space) in Mathlib.LinearAlgebra.AffineSpace.Simplex.Basic. It is NOT the figurate \"simplex number\" the Wikifunction computes. All four tagged decls (Affine.Simplex, Affine.Triangle, stdSimplex, convex_stdSimplex) are geometric/topological simplex objects mis-matched on the word \"simplex.\" The WF \"nth r-simplex number\" (Q331350, simplicial/figurate number) returns the ℕ value C(n+r-1, r) = n(n+1)...(n+r-1)/r!. The correct oracle is the binomial coefficient Nat.choose (n + r - 1) r, equivalently Nat.multichoose n r (proved equal by Nat.multichoose_eq). Signature (ℕ,ℕ)→ℕ is faithful to the concept; only the tagged Lean target is wrong.",
    tier: "composite_provable",
  },
  {
    zid: "Z15849",
    qid: "Q192826",
    name: "Kronecker delta",
    oracleDecl: "fun (i j : ℕ) => (if i = j then 1 else 0 : ℕ)  -- equivalently (1 : Matrix ℕ ℕ ℕ) i j, characterized by Matrix.one_apply",
    docDecl: "Matrix.one_apply",
    computable: "computable_nat_int",
    faithfulness: "faithful",
    faithfulnessNote: "Concept matches exactly. Mathlib has no standalone `Kronecker.delta`; the Kronecker delta is encoded as the entries of the identity matrix. `Matrix.one_apply` (Diagonal.lean:234, inside `namespace Matrix`, line 35) is verbatim and states `(1 : Matrix n n α) i j = if i = j then 1 else 0`, proved by `rfl`. Over `n = ℕ`, `α = ℕ` this is exactly the WF `(ℕ,ℕ)→ℕ` delta. Caveat: `one_apply` is a theorem ABOUT matrix entries (over arbitrary indexed type + semiring with `DecidableEq`), not a literal `ℕ→ℕ→ℕ` function — but it pins the defining equation precisely, so the computable oracle is the bare `if i = j then 1 else 0 : ℕ`. Secondary decls one_apply_eq (238), one_apply_ne (242), diagonal (def, 50) all exist verbatim.",
    tier: "composite_provable",
  },
  {
    zid: "Z18194",
    qid: "Q205170",
    name: "powerset",
    oracleDecl: "Finset.powerset",
    docDecl: "Finset.powerset",
    computable: "computable_nat_int",
    faithfulness: "representation_mismatch",
    faithfulnessNote: "Concept (powerset = set of all subsets) is correct. primary_decl Set.powerset EXISTS verbatim at Mathlib/Data/Set/Defs.lean:256 inside `namespace Set` (def powerset (s : Set α) : Set (Set α) := {t | t ⊆ s}, notation 𝒫 s), but it returns Set (Set α) = a Prop-valued predicate over subsets, which is non-enumerable and NOT computable — it cannot produce the concrete finite list of subsets the Wikifunction returns. The faithful COMPUTABLE oracle is the secondary_decl Finset.powerset (Mathlib/Data/Finset/Powerset.lean:32): def powerset (s : Finset α) : Finset (Finset α), built on Multiset.powerset, with defining property Finset.mem_powerset : s ∈ powerset t ↔ s ⊆ t and Finset.card_powerset : card (powerset s) = 2^card s. Not wrong_target (Set.powerset is a real def, not a typeclass); it is the right concept encoded as Set vs the finite/enumerable Finset the WF actually computes.",
    tier: "composite_provable",
  },
  {
    zid: "Z20000",
    qid: "Q182505",
    name: "Bayes' theorem",
    oracleDecl: "fun (pBA pA pB : ℚ) => pBA * pA / pB",
    docDecl: "",
    computable: "computable_nat_int",
    faithfulness: "representation_mismatch",
    faithfulnessNote: "primary_decl ProbabilityTheory.cond_eq_inv_mul_cond_mul EXISTS verbatim at Mathlib/Probability/ConditionalProbability.lean:273 as a theorem: `μ[t | s] = (μ s)⁻¹ * μ[s | t] * μ t` over ℝ≥0∞. Correct CONCEPT (Bayes' theorem, tagged with `## Tags: bayes`) but it is the abstract measure-theoretic identity, not a computable function. The Wikifunction signature is (ℚ,ℚ,ℚ)→ℚ: given the likelihood P(B|A), prior P(A), and evidence P(B), it returns the posterior P(A|B) = P(B|A)·P(A)/P(B) — the arithmetic/numeric form of Bayes' rule. Same identity, different representation (concrete rational arithmetic vs Mathlib measures/sets/ℝ≥0∞). The whole ConditionalProbability section is `noncomputable section`, so the theorem itself yields no kernel-evaluable oracle; the value the WF returns is plain ℚ-field arithmetic. Not a typeclass (so not wrong_target); secondary_decl posterior_eq_withDensity (Mathlib/Probability/Kernel/Posterior.lean:287) is the kernel-posterior version, even further from a ℚ→ℚ function.",
    tier: "composite_provable",
  },
  {
    zid: "Z28925",
    qid: "Q208225",
    name: "is Pythagorean triple",
    oracleDecl: "decide (a * a + b * b = c * c)  -- equiv to PythagoreanTriple over ℤ; for the Mathlib decl use: decide (PythagoreanTriple (a:ℤ) b c)",
    docDecl: "PythagoreanTriple",
    computable: "decidable",
    faithfulness: "faithful",
    faithfulnessNote: "primary_decl `PythagoreanTriple` exists verbatim at line 43: `def PythagoreanTriple (x y z : ℤ) : Prop := x * x + y * y = z * z`. It is the correct predicate, not a typeclass and not a string/float encoding. Two minor caveats: (a) it is a Prop not a Bool, but it is decidable (DecidableEq ℤ), so `decide (PythagoreanTriple ...)` yields the Boolean the WF returns; the surrounding `noncomputable section` marks the deep classification machinery noncomputable but does NOT affect decidability of this equality Prop. (b) Mathlib uses ℤ whereas the WF uses ℕ — a strict generalization; for natural inputs the two coincide via Nat→Int casts. Hence faithful with a domain-widening note rather than representation_mismatch.",
    tier: "composite_provable",
  },
  {
    zid: "Z10862",
    qid: "Q40276",
    name: "multiply numeric strings",
    oracleDecl: "HMul.hMul (or Nat.mul / Int.mul); for the decimal \"full stop\" format, Rat multiplication (· * ·) on ℚ",
    docDecl: "HMul.hMul",
    computable: "computable_nat_int",
    faithfulness: "wrong_target",
    faithfulnessNote: "primary_decl \"Mul\" is the heterogeneous-multiplication TYPECLASS (Lean core, Init.Prelude), not the operation that computes a product — so it is a wrong_target. It is ALSO mis-cited: \"Mul\" is NOT defined in Mathlib.Algebra.Group.Defs (that module defines Semigroup/Monoid/CommMonoid/mul_comm, where `Semigroup extends Mul`). On top of the typeclass problem there is a representation_mismatch: the WF signature (String, String) -> String encodes numbers as decimal-digit strings with a \"full stop\" (decimal point) separator, whereas the Mathlib concept is multiplication of ℕ/ℤ/ℚ values. The \"(!)\" in the label is the WF community flag for exactly this awkward string I/O. The correct oracle is the concrete `*` (HMul.hMul) on ℕ/ℤ for integers, or ℚ for the decimal-point variant.",
    tier: "oracle_testable",
  },
  {
    zid: "Z12665",
    qid: "Q33456",
    name: "exponentiation",
    oracleDecl: "(· ^ ·) on Float   ·   ideal: Real.rpow",
    docDecl: "Real.rpow",
    computable: "float",
    faithfulness: "faithful",
    faithfulnessNote: "Float oracle (Lean `Float`, IEEE-754 binary64) matches the WF's float64 representation — resolves the earlier real-vs-float mismatch. A `noncomputable` `Real` ideal documents the exact mathematical function it approximates (within ~1 ULP across libms). primary_decl Monoid.npow exists verbatim as a FIELD of `class Monoid` at Mathlib/Algebra/Group/Defs.lean:657 (`protected npow : ℕ → M → M := npowRecAuto`), but it is the wrong target on two counts. (1) It is a typeclass-field construct describing power-by-a-NATURAL-NUMBER (x ^ (n : ℕ)) in an abstract monoid — the exponent type is ℕ. The Wikifunction is `(float64, float64) -> float64`: BOTH the base and the exponent are reals, so the concept is real-to-real exponentiation, not monoid^nat. (2) Even as a Pow operation, npow is exposed via the abstract `Monoid.toPow` instance, not the concrete operation. The faithful oracle is `Real.rpow` (already listed among secondary_decls), `noncomputable def rpow (x y : ℝ) := ((x:ℂ)^(y:ℂ)).re`, which is exactly ℝ×ℝ→ℝ exponentiation. There is also a secondary representation_mismatch: the WF uses float64 where Mathlib uses exact ℝ (so for negative bases with non-integer exponents the WF/IEEE result, e.g. NaN, will diverge from Real.rpow's branch-cut convention exp(log x · y)·cos(π y)).",
    tier: "oracle_testable",
  },
  {
    zid: "Z13341",
    qid: "Q2266329",
    name: "linear interpolation",
    oracleDecl: "(1 - t)·a + t·b on Float   ·   ideal: AffineMap.lineMap",
    docDecl: "AffineMap.lineMap",
    computable: "float",
    faithfulness: "faithful",
    faithfulnessNote: "Float oracle (Lean `Float`, IEEE-754 binary64) matches the WF's float64 representation — resolves the earlier real-vs-float mismatch. A `noncomputable` `Real` ideal documents the exact mathematical function it approximates (within ~1 ULP across libms). Concept matches exactly: lerp(a,b,t) = (1-t)*a + t*b is precisely AffineMap.lineMap a b t specialized to the scalar/ring case (AffineMap.lineMap_apply_ring: lineMap a b c = (1 - c) * a + c * b; lineMap_apply_ring': = c * (b - a) + a). primary_decl is the genuine interpolation map, NOT a typeclass, so it is the right target. The mismatch is purely representational: the Wikifunction operates over float64, which the faithful Mathlib model treats as ℝ (real arithmetic is noncomputable in Lean). Over a computable field (ℚ) lineMap is a plain `def` and does evaluate, but float64 semantics ≅ ℝ. Argument order: lineMap p₀ p₁ applied at c, i.e. endpoint a, endpoint b, parameter t.",
    tier: "oracle_testable",
  },
  {
    zid: "Z21003",
    qid: "Q204037",
    name: "natural logarithm",
    oracleDecl: "Float.log   ·   ideal: Real.log",
    docDecl: "Real.log",
    computable: "float",
    faithfulness: "faithful",
    faithfulnessNote: "Float oracle (Lean `Float`, IEEE-754 binary64) matches the WF's float64 representation — resolves the earlier real-vs-float mismatch. A `noncomputable` `Real` ideal documents the exact mathematical function it approximates (within ~1 ULP across libms). Concept matches: WF \"natural logarithm (float64)\" = Real.log, the natural log. Two caveats. (1) Representation: WF is (float64)->float64 (finite-precision floats); Mathlib's Real.log : ℝ → ℝ is the exact real-valued, NONCOMPUTABLE function (defined via expOrderIso.symm, the inverse of Real.exp). The Lean kernel cannot evaluate it on concrete inputs, so it serves only as an exact spec, not a bit-for-bit oracle for float arithmetic. (2) Totalization differs: Mathlib's Real.log is total — log 0 = 0 and log x = log |x| for x < 0 — whereas the WF natural log is conventionally defined only for x > 0 (float impl likely returns NaN/error for x ≤ 0). Correspondence holds cleanly only on the positive domain via Real.exp_log / Real.log_exp.",
    tier: "oracle_testable",
  },
  {
    zid: "Z21005",
    qid: "Q966582",
    name: "log base 10",
    oracleDecl: "Float.log x / Float.log 10   ·   ideal: Real.logb 10",
    docDecl: "Real.logb",
    computable: "float",
    faithfulness: "faithful",
    faithfulnessNote: "Float oracle (Lean `Float`, IEEE-754 binary64) matches the WF's float64 representation — resolves the earlier real-vs-float mismatch. A `noncomputable` `Real` ideal documents the exact mathematical function it approximates (within ~1 ULP across libms). primary_decl Real.logb is the correct operation (the real logarithm in a given base, def logb b x := log x / log b), NOT a typeclass — so this is not wrong_target. Base-10 log = Real.logb 10. The only mismatch is encoding: the Wikifunction is typed (float64) -> float64 (finite-precision IEEE-754) whereas Mathlib's logb operates on exact ℝ. Concept is faithful; representation differs (float vs ℝ), and floats only approximate the real value. logb is noncomputable (sits in a `noncomputable section`, defined via Real.log).",
    tier: "oracle_testable",
  },
  {
    zid: "Z21917",
    qid: "Q381040",
    name: "complex conjugate (integer pair)",
    oracleDecl: "fun p : ℤ × ℤ => (p.1, -p.2)  -- integer-pair conjugation; corresponds to starRingEnd ℂ via conj_re/conj_im (Complex.star z = ⟨z.re, -z.im⟩)",
    docDecl: "starRingEnd",
    computable: "computable_nat_int",
    faithfulness: "representation_mismatch",
    faithfulnessNote: "primary_decl starRingEnd EXISTS verbatim (Mathlib/Algebra/Star/Basic.lean:337, `def starRingEnd : R →+* R`), and starRingEnd ℂ = conj IS complex conjugation, so the concept is right. But the WF signature is (Integer, Integer) -> ? : a complex number encoded as a PAIR/LIST of two ℤ (Gaussian-integer encoding), conjugated as (a,b)↦(a,-b). Mathlib's ℂ is a structure of two ℝ (re,im : ℝ) with star z = ⟨z.re, -z.im⟩ (Data/Complex/Basic.lean:460). Same operation (negate imaginary part) but over ℤ×ℤ vs ℝ×ℝ → representation_mismatch. starRingEnd itself is also a generic ring endomorphism (typeclass-bundled hom), not the bare scalar op, but here it does denote the actual conjugation so it is not wrong_target.",
    tier: "oracle_testable",
  },
  {
    zid: "Z30840",
    qid: "Q19033",
    name: "arithmetic mean",
    oracleDecl: "fun (l : List ℕ) => ((l.map (Nat.cast : ℕ → ℚ)).sum) / (l.length : ℚ)",
    docDecl: "",
    computable: "computable_nat_int",
    faithfulness: "wrong_target",
    faithfulnessNote: "primary_decl MeasureTheory.average exists verbatim (Mathlib/MeasureTheory/Integral/Average.lean:279, inside `namespace MeasureTheory`) but is `noncomputable def average (f : α → E) := ∫ x, f x ∂(μ univ)⁻¹ • μ` — the Bochner integral average of a FUNCTION over a MEASURE space. The Wikifunction Z30840 computes the elementary arithmetic mean of a finite collection of natural numbers, returned exactly as a Rational = (Σ aᵢ)/n. That is a finite, fully computable rational, completely unrelated to a measure-theoretic integral. Secondary MeasureTheory.laverage has the same problem. Finset.centerMass ((Σ w i)⁻¹ • Σ w i • z i) is the closest Mathlib object (with all weights 1 it IS the arithmetic mean) but is a weighted center-of-mass over a module, not a list→ℚ mean. Real.inner_le_..._arith_mean_pow is an AM-GM inequality, not a mean. Mathlib has no dedicated named 'arithmetic mean of a list as ℚ' decl, so the oracle is composed from computable primitives (List.sum cast to ℚ, divided by length).",
    tier: "oracle_testable",
  },
  {
    zid: "Z31173",
    qid: "Q852973",
    name: "Euler characteristic",
    oracleDecl: "(fun (V E F : ℕ) => (V : ℤ) - (E : ℤ) + (F : ℤ))  -- elementary V - E + F; no dedicated Mathlib decl exists",
    docDecl: "",
    computable: "computable_nat_int",
    faithfulness: "wrong_target",
    faithfulnessNote: "primary_decl HomologicalComplex.eulerChar EXISTS verbatim (noncomputable abbrev, line 147 of Mathlib/Algebra/Homology/EulerCharacteristic.lean) but is the WRONG target: it is the abstract homological-algebra Euler characteristic — an alternating-sign finsum of Module.finrank of the objects of a HomologicalComplex over ModuleCat R. It takes a chain complex (not three ℕ) and is noncomputable. The Wikifunction is the elementary polyhedron formula V - E + F : (ℕ,ℕ,ℕ)→ℤ (Q852973 = Euler's polyhedron theorem). docs/1000.yaml line 966-967 maps Q852973 to \"Euler's polyhedron theorem\" with NO decls field, i.e. Mathlib does not formalize it. Secondary decls (GradedObject.eulerChar, ComplexShape.EulerCharSigns, homologyEulerChar) are all part of the same homological-algebra file and equally off-target; IncidenceAlgebra.eulerChar is yet another (poset Möbius) notion. None matches the ℕ³→ℤ V-E+F function.",
    tier: "oracle_testable",
  },
  {
    zid: "Z35278",
    qid: "Q204570",
    name: "Shannon entropy",
    oracleDecl: "∑ negMulLog over Float (bits)   ·   ideal: Real.negMulLog",
    docDecl: "Real.negMulLog",
    computable: "float",
    faithfulness: "faithful",
    faithfulnessNote: "Float oracle (Lean `Float`, IEEE-754 binary64) matches the WF's float64 representation — resolves the earlier real-vs-float mismatch. A `noncomputable` `Real` ideal documents the exact mathematical function it approximates (within ~1 ULP across libms). primary_decl Real.negMulLog exists verbatim (NegMulLog.lean:164, namespace Real, noncomputable def negMulLog x = -x*log x) and is the per-term summand of Shannon entropy — its docstring even names Shannon entropy. But it is NOT the value the WF returns: the WF computes the FULL entropy of a string = ∑ over distinct chars of negMulLog(count/len). Mathlib has no string/list/empirical-distribution Shannon entropy def (grep of all *.lean found only NegMulLog.lean and BinaryEntropy.lean). Secondary decls Real.binEntropy and Real.qaryEntropy are the Bernoulli (q=2) and q-ary special cases, not a general empirical distribution. Hence representation_mismatch: WF operates String→float64 while the Mathlib building block is ℝ→ℝ and the aggregate must be assembled. Additional units caveat: Mathlib uses natural log (nats); Shannon-entropy-from-string conventionally uses log base 2 (bits) — handled via Real.logb 2 in the spec.",
    tier: "oracle_testable",
  },
  {
    zid: "Z16483",
    qid: "Q190573",
    name: "gamma function",
    oracleDecl: "Real.Gamma",
    docDecl: "Real.Gamma",
    computable: "noncomputable_real",
    faithfulness: "representation_mismatch",
    faithfulnessNote: "Concept matches: Complex.Gamma (and Real.Gamma) is exactly the Γ function. But the Wikifunction has signature String -> String, encoding a real/complex transcendental value as a decimal string. That is a representation_mismatch vs Mathlib's Real.Gamma : ℝ → ℝ / Complex.Gamma : ℂ → ℂ. The \"(!)\" in the WF label flags it as community-problematic (string encoding of a numeric special function). Real.Gamma is the more faithful oracle since WF returns a single decimal value, not a complex pair.",
    tier: "spec_only",
  },
];
