#!/usr/bin/env python3
"""Cross-language parity contract — Python side.

wiki/test/fixtures/parity.json is the contract: a table of cases whose
expected values were generated by RUNNING the current implementations on both
sides. This suite replays every case through the Python twins:

    moderate._anchor_sig          (and batch_annotate._anchor_sig, asserted
                                   identical whenever the SDK is importable)
    python dict ==                (the deep-equality _preserve_human and
                                   finalize_for_post actually use)
    moderate.finalize_for_post    (ID discipline + wire-level human preservation)
    batch_annotate._preserve_human (ladder pass; skips without the SDK)

wiki/test/parity.test.ts replays the SAME file through the TS helpers
(anchorSig / deepEqual / findMatch / findLostHuman / stampProvenance). Any
future drift between the three implementations fails one side of the contract.

Language-scoped expectations ({"py": X, "ts": Y}) and "py_raises" pins mark
KNOWN divergences — places where the languages genuinely disagree today; each
carries a known_divergence note with file:line on both sides. This suite
asserts the divergence still EXISTS (e.g. the pinned crash still crashes):
fixing one in source must come with a fixture update. That is the contract
working, not an obstacle.

No pytest dependency required:
    python3 site/test_parity.py
    python3 -m pytest site/test_parity.py    # also works
"""
from __future__ import annotations

import copy
import json
import re
import sys
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import moderate as m  # noqa: E402  (stdlib-only at import time)

try:
    import batch_annotate as ba
except ImportError:
    ba = None

FIXTURE_PATH = HERE.parent / "wiki" / "test" / "fixtures" / "parity.json"
FIXTURE = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))
CASES = FIXTURE["cases"]
HEX12_RE = re.compile(r"^[0-9a-f]{12}$")

KNOWN_FNS = {"anchor_sig", "sig_equal", "deep_equal", "find_match",
             "lost_human", "stamp_provenance", "finalize", "preserve_human"}


def runs_here(c: dict) -> bool:
    return "py" in c.get("langs", ["py", "ts"])


def by_fn(fn: str) -> list[dict]:
    return [c for c in CASES if c["fn"] == fn and runs_here(c)]


def for_py(v):
    """Unwrap a language-scoped expectation ({"py": X, "ts": Y}) to py's pin."""
    if isinstance(v, dict) and v and set(v) <= {"py", "ts"}:
        assert "py" in v, f"expectation scoped away from py: {v}"
        return v["py"]
    return v


def sigs(a: dict) -> str:
    """moderate._anchor_sig, asserting batch_annotate stays in lockstep."""
    s = m._anchor_sig(a)
    if ba is not None:
        assert ba._anchor_sig(a) == s, f"moderate/batch_annotate sig drift on {a}"
    return s


# ---------------------------------------------------------------------------
# fn groups
# ---------------------------------------------------------------------------

def test_anchor_sig_cases():
    for c in by_fn("anchor_sig"):
        exp = c["expect"]
        if "py_raises" in exp:
            # KNOWN DIVERGENCE pin: python crashes where ts returns the
            # all-null sig. Assert the crash still happens (in BOTH python
            # twins) so a silent fix can't leave the fixture stale.
            for fn_impl in [m._anchor_sig] + ([ba._anchor_sig] if ba else []):
                try:
                    fn_impl(copy.deepcopy(c["a"]))
                    raise AssertionError(
                        f"{c['name']}: expected {exp['py_raises']}, got no error — "
                        f"divergence fixed in source? Update the fixture pin.")
                except AssertionError:
                    raise
                except Exception as e:  # noqa: BLE001 — pinning the class
                    assert type(e).__name__ == exp["py_raises"], (c["name"], e)
        else:
            assert sigs(c["a"]) == exp["sig"]["py"], c["name"]


def test_sig_equal_cases():
    for c in by_fn("sig_equal"):
        exp = c["expect"]
        if "py_raises" in exp:
            continue  # crash pinned by the anchor_sig group
        got = sigs(c["a"]) == sigs(c["b"])
        assert got == for_py(exp["sig_equal"]), (
            f"{c['name']}: sig_equal {got} != {for_py(exp['sig_equal'])}")


def test_deep_equal_cases():
    # python dict == IS the deep-equality twin (used by _preserve_human's
    # `out[i] != restored` and finalize_for_post's `a != h` stats counting).
    for c in by_fn("deep_equal"):
        want = for_py(c["expect"]["deep_equal"])
        assert (c["a"] == c["b"]) == want, c["name"]
        assert (c["b"] == c["a"]) == want, f"{c['name']} (symmetric)"


def test_ts_only_cases_are_marked():
    # find_match / lost_human / stamp_provenance have no standalone Python
    # twin (matching lives inline in finalize_for_post; stamping and the 422
    # are server-side). The fixture must scope them away from py explicitly —
    # if a Python twin ever lands, these cases get langs ["py","ts"] and a
    # runner branch here.
    for fn in ("find_match", "lost_human", "stamp_provenance"):
        for c in (x for x in CASES if x["fn"] == fn):
            assert c.get("langs") == ["ts"], (
                f"{c['name']}: fn={fn} must be ts-scoped (no python twin)")
    assert not by_fn("find_match") and not by_fn("lost_human")


def _check_finalize_out(name: str, existing: list, produced: list,
                        out: list, expected_out: list) -> None:
    known_ids = {a.get("id") for a in existing if isinstance(a.get("id"), str)}
    known_ids |= {a.get("id") for a in produced if isinstance(a.get("id"), str)}
    assert len(out) == len(expected_out), (
        f"{name}: {len(out)} annotations != expected {len(expected_out)}")
    fresh_seen: set[str] = set()
    for i, (got, want) in enumerate(zip(out, expected_out)):
        if want.get("id") == "<FRESH>":
            aid = got.get("id")
            assert isinstance(aid, str) and HEX12_RE.match(aid), (name, i, aid)
            assert aid not in known_ids, f"{name}[{i}]: fresh id collided with a known id"
            assert aid not in fresh_seen, f"{name}[{i}]: fresh id minted twice"
            fresh_seen.add(aid)
            got = {**got, "id": "<FRESH>"}
        assert got == want, f"{name}[{i}]:\n  got  {got}\n  want {want}"


def test_finalize_cases():
    for c in by_fn("finalize"):
        out, stats = m.finalize_for_post(copy.deepcopy(c["existing"]),
                                         copy.deepcopy(c["produced"]))
        _check_finalize_out(c["name"], c["existing"], c["produced"],
                            out, c["expect"]["out"])
        assert stats == c["expect"]["stats"], (
            f"{c['name']}: stats {stats} != {c['expect']['stats']}")
        # The ts side of the same case proves expect.out passes findLostHuman
        # (lost_human_after == []) — i.e. the pinned wire payload can't 422.
        assert c["expect"]["lost_human_after"] == [], c["name"]


def test_preserve_human_cases():
    if ba is None:
        raise unittest.SkipTest("claude-agent-sdk not installed")
    for c in by_fn("preserve_human"):
        out, stats = ba._preserve_human(copy.deepcopy(c["existing"]),
                                        copy.deepcopy(c["produced"]))
        assert out == c["expect"]["out"], (
            f"{c['name']}:\n  got  {out}\n  want {c['expect']['out']}")
        assert stats == c["expect"]["stats"], (c["name"], stats)


def test_fixture_hygiene():
    names = set()
    for c in CASES:
        assert c["fn"] in KNOWN_FNS, (c["name"], c["fn"])
        assert c["name"] not in names, f"duplicate case name {c['name']}"
        names.add(c["name"])
        # Semantic divergences (scoped equality booleans / pinned crashes)
        # must each carry a known_divergence note. expect.sig is scoped on
        # every case by design (json.dumps vs JSON.stringify formatting,
        # documented once in _doc) and exempt.
        exp = c["expect"]
        diverges = "py_raises" in exp or any(
            isinstance(exp.get(k), dict) and set(exp[k]) == {"py", "ts"}
            and exp[k]["py"] != exp[k]["ts"]
            for k in ("sig_equal", "deep_equal"))
        if diverges:
            assert c.get("known_divergence"), (
                f"{c['name']} diverges but carries no known_divergence note")


def test_every_case_is_executed_somewhere():
    # No case may be scoped out of BOTH languages.
    for c in CASES:
        langs = c.get("langs", ["py", "ts"])
        assert langs and set(langs) <= {"py", "ts"}, (c["name"], langs)


# ---------------------------------------------------------------------------
# plain runner (no pytest needed) — mirrors test_moderate.py
# ---------------------------------------------------------------------------

def main() -> int:
    tests = [(n, f) for n, f in sorted(globals().items())
             if n.startswith("test_") and callable(f)]
    passed = failed = skipped = 0
    for name, fn in tests:
        try:
            fn()
            passed += 1
            print(f"  PASS {name}")
        except unittest.SkipTest as e:
            skipped += 1
            print(f"  SKIP {name} ({e})")
        except AssertionError as e:
            failed += 1
            print(f"  FAIL {name}: {e}")
    n_div = sum(1 for c in CASES if c.get("known_divergence"))
    print(f"\n{passed} passed, {failed} failed, {skipped} skipped "
          f"({len(CASES)} fixture cases, {n_div} known divergences pinned)")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
