#!/usr/bin/env python3
"""FormalConjectures frontier ingest: map DeepMind's conjecture statements to
Wikidata QIDs via the Wikipedia articles their own module docs cite.

Source: the CORS-open dump at
https://google-deepmind.github.io/formal-conjectures/data/conjectures.json
(3,071 attribute-tagged statements; regenerated by their CI on every push).
The FC repo contains ZERO Wikidata references — this mapping is the unclaimed
territory the research sweep identified, and the outreach artifact for the
TheoremGraph/FC communities.

Anti-slop rules (deterministic, no LLM):
- Only `research open` / `research solved` statements (test/API/textbook are
  benchmark scaffolding, not frontier mathematics).
- A module maps ONLY if its docs cite exactly ONE distinct enwiki article —
  multi-URL modules go to fc_review.jsonl for a human, never to the graph.
- The title→QID join is verified by the MediaWiki API itself: redirects=1
  resolves to the canonical page and pageprops.wikibase_item is that page's
  own item — an exact join, not a guess. Pages with no item are dropped.
- `research solved` means informally accepted, NOT formally proved — the
  category rides every row and the UI must never render it as 'proved'.

Output: catalog/data/fc_tagged.jsonl (one row per statement) + fc_review.jsonl.
Atomic writes; run nightly before the graph build. Prints category drift vs
the previous run (open→solved flips are the frontier moving).
"""
import json
import re
import subprocess
import sys
import time
import urllib.parse
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
OUT = DATA / "fc_tagged.jsonl"
REVIEW = DATA / "fc_review.jsonl"
DUMP_URL = "https://google-deepmind.github.io/formal-conjectures/data/conjectures.json"
WP_API = "https://en.wikipedia.org/w/api.php"
UA = "WikiLean-fc-ingest/1.0 (https://wikilean.jackmccarthy.org; jack.mccarthy.1@stonybrook.edu)"
KEEP = {"research open", "research solved"}
WIKI_RE = re.compile(r"https://en\.wikipedia\.org/wiki/([^\"\\\s<)#]+)")


def curl_json(url: str) -> dict:
    out = subprocess.run(["curl", "-sS", "-m", "120", "--retry", "2",
                          "-H", f"User-Agent: {UA}", url],
                         capture_output=True, text=True, timeout=180, check=True).stdout
    return json.loads(out)


def resolve_qids(titles: list[str]) -> dict[str, tuple[str, str]]:
    """raw title → (canonical_title, qid) via MediaWiki (redirects resolved).
    The wikibase_item pageprop belongs to the canonical page itself, so the
    join is exact by construction. Titles without an item are omitted."""
    resolved: dict[str, tuple[str, str]] = {}
    for i in range(0, len(titles), 50):
        chunk = titles[i:i + 50]
        q = urllib.parse.urlencode({
            "action": "query", "format": "json", "redirects": 1,
            "prop": "pageprops", "ppprop": "wikibase_item",
            "titles": "|".join(chunk)})
        d = curl_json(f"{WP_API}?{q}")["query"]
        # normalization + redirect maps recover each ORIGINAL title's target
        follow: dict[str, str] = {}
        for m in d.get("normalized", []) + d.get("redirects", []):
            follow[m["from"]] = m["to"]
        pages = {p["title"]: p for p in d.get("pages", {}).values()}
        for t in chunk:
            target = t
            seen = set()
            while target in follow and target not in seen:
                seen.add(target)
                target = follow[target]
            page = pages.get(target)
            qid = (page or {}).get("pageprops", {}).get("wikibase_item")
            if qid:
                resolved[t] = (target, qid)
        time.sleep(0.5)
    return resolved


def main() -> int:
    dump = curl_json(DUMP_URL)
    recs = [r for r in dump["conjectures"] if r.get("category") in KEEP]
    module_docs = dump["versoFragments"]["moduleDocs"]
    # module path "/FormalConjectures/Wikipedia/CollatzConjecture/" → dotted module
    mod_urls: dict[str, list[str]] = {}
    for path, html in module_docs.items():
        titles = sorted({urllib.parse.unquote(m.group(1)).replace("_", " ")
                         for m in WIKI_RE.finditer(html if isinstance(html, str) else json.dumps(html))})
        if titles:
            mod_urls[path.strip("/").replace("/", ".")] = titles
    single = {m: ts[0] for m, ts in mod_urls.items() if len(ts) == 1}
    multi = {m: ts for m, ts in mod_urls.items() if len(ts) > 1}
    print(f"{len(recs)} frontier statements; {len(mod_urls)} modules cite enwiki "
          f"({len(single)} single-URL → auto, {len(multi)} multi-URL → review)")

    qids = resolve_qids(sorted(set(single.values())))
    print(f"resolved {len(qids)}/{len(set(single.values()))} titles to QIDs")

    prev_cat: dict[str, str] = {}
    if OUT.exists():
        for line in OUT.read_text().splitlines():
            if line.strip():
                r = json.loads(line)
                prev_cat[r["fc_decl"]] = r["category"]

    rows, review = [], []
    for r in recs:
        mod = r["displayModule"]
        subjects = r.get("subjects")
        if isinstance(subjects, str):  # dump quirk: python-repr string
            try:
                subjects = json.loads(subjects.replace("'", '"'))
            except ValueError:
                subjects = []
        ams = [s.get("code") for s in (subjects or []) if isinstance(s, dict)]
        base = {"fc_decl": r["theorem"], "module": mod, "category": r["category"],
                "ams": ams, "github_url": r.get("githubUrl") or "",
                "collection": r.get("collection") or ""}
        if mod in single and single[mod] in qids:
            canon, qid = qids[single[mod]]
            rows.append({**base, "qid": qid, "wp_title": canon,
                         "provenance": "fc-moduledocs-singleurl"})
        elif mod in multi:
            review.append({**base, "candidate_titles": multi[mod]})
    # category drift vs the previous run — the frontier moving is the signal
    for row in rows:
        old = prev_cat.get(row["fc_decl"])
        if old and old != row["category"]:
            print(f"  DRIFT {row['fc_decl']}: {old} → {row['category']}")

    for path, data in ((OUT, rows), (REVIEW, review)):
        tmp = path.with_suffix(".tmp")
        tmp.write_text("".join(json.dumps(x, ensure_ascii=False) + "\n" for x in data))
        tmp.replace(path)
    n_qids = len({r["qid"] for r in rows})
    print(f"wrote {OUT.name}: {len(rows)} statements → {n_qids} QIDs; "
          f"{REVIEW.name}: {len(review)} for review")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
