// Cross-language parity contract — TS side (P1/P2 eval harness).
//
// wiki/test/fixtures/parity.json is the contract: a table of cases whose
// expected values were generated by RUNNING the current implementations on
// both sides. This suite replays every case through the real validation.ts
// helpers; site/test_parity.py replays the SAME file through the Python twins
// (moderate._anchor_sig / finalize_for_post, batch_annotate._anchor_sig /
// _preserve_human). Any future drift between the three implementations fails
// one side of the contract.
//
// Language-scoped expectations ({py: X, ts: Y}) mark KNOWN divergences —
// places where the two languages genuinely disagree today. Each case's
// known_divergence field documents the finding with file:line on both sides.
// Fixing a divergence in source requires updating the fixture pin: that is
// the contract working, not an obstacle.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it, expect } from "vitest";
import {
  anchorSig,
  deepEqual,
  findMatch,
  findLostHuman,
  stampProvenance,
  type AnnRecord,
} from "../src/validation.js";

interface ParityCase {
  name: string;
  fn: string;
  why?: string;
  langs?: string[];
  known_divergence?: string;
  a?: AnnRecord;
  b?: AnnRecord;
  target?: AnnRecord;
  pool?: AnnRecord[];
  stored?: AnnRecord[];
  posted?: AnnRecord[];
  existing?: AnnRecord[];
  produced?: AnnRecord[];
  expect: Record<string, unknown>;
}

const fixture = JSON.parse(
  readFileSync(resolve(process.cwd(), "test/fixtures/parity.json"), "utf8"),
) as { _schema: string; cases: ParityCase[] };

// Unwrap a language-scoped expectation ({py, ts}) to this side's pin.
function forTs(v: unknown): unknown {
  if (v !== null && typeof v === "object" && !Array.isArray(v)) {
    const o = v as Record<string, unknown>;
    const keys = Object.keys(o);
    if (keys.length > 0 && keys.every((k) => k === "py" || k === "ts")) return o.ts;
  }
  return v;
}

const runsHere = (c: ParityCase): boolean => (c.langs ?? ["py", "ts"]).includes("ts");
const byFn = (fn: string): ParityCase[] => fixture.cases.filter((c) => c.fn === fn && runsHere(c));
const title = (c: ParityCase): string => (c.known_divergence ? `${c.name} [KNOWN DIVERGENCE]` : c.name);

// Materialize a pinned finalize output: '<FRESH>' ids become distinct valid
// 12-hex ids (their exact value is irrelevant to the 422 cross-check).
function materialize(out: AnnRecord[]): AnnRecord[] {
  let n = 0;
  return out.map((a) => (a.id === "<FRESH>" ? { ...a, id: `f${(n++).toString(16).padStart(11, "0")}` } : a));
}

describe("parity: anchorSig", () => {
  for (const c of byFn("anchor_sig")) {
    it(title(c), () => {
      // Every case pins a ts sig. (Until fix F12 two cases pinned a Python
      // AttributeError here instead — non-dict anchors no longer crash and
      // anchors[0] is the lockstep fallback in both languages.)
      const sig = (c.expect.sig as Record<string, string>).ts;
      expect(sig).toBeDefined();
      expect(anchorSig(c.a!)).toBe(sig);
    });
  }
});

describe("parity: sig equality structure", () => {
  for (const c of byFn("sig_equal")) {
    it(title(c), () => {
      expect(anchorSig(c.a!) === anchorSig(c.b!)).toBe(forTs(c.expect.sig_equal));
    });
  }
});

describe("parity: deepEqual", () => {
  for (const c of byFn("deep_equal")) {
    it(title(c), () => {
      expect(deepEqual(c.a, c.b)).toBe(forTs(c.expect.deep_equal));
      // deepEqual is symmetric; pin both directions so an asymmetry regression
      // (e.g. a one-sided key-subset check) can't hide.
      expect(deepEqual(c.b, c.a)).toBe(forTs(c.expect.deep_equal));
    });
  }
});

describe("parity: findMatch (id-vs-sig precedence)", () => {
  for (const c of byFn("find_match")) {
    it(title(c), () => {
      const m = findMatch(c.target!, c.pool!);
      expect(m !== undefined).toBe(c.expect.match_found);
      const idx = m === undefined ? null : c.pool!.indexOf(m);
      expect(idx).toBe(c.expect.match_index);
    });
  }
});

describe("parity: findLostHuman (the server 422)", () => {
  for (const c of byFn("lost_human")) {
    it(title(c), () => {
      expect(findLostHuman(c.stored!, c.posted!)).toEqual(c.expect.lost_human);
    });
  }
});

describe("parity: stampProvenance (anti-laundering)", () => {
  for (const c of byFn("stamp_provenance")) {
    it(title(c), () => {
      const stamped = stampProvenance(c.stored!, c.posted!);
      expect(stamped.map((a) => a.provenance)).toEqual(c.expect.provenance);
      // Stamping must not touch anything except provenance.
      for (let i = 0; i < stamped.length; i++) {
        const { provenance: _sp, ...stampedRest } = stamped[i];
        const { provenance: _pp, ...postedRest } = c.posted![i];
        expect(stampedRest).toEqual(postedRest);
      }
    });
  }
});

describe("parity: finalize_for_post output honors the 422 contract", () => {
  // Python executes finalize_for_post and pins its output in expect.out; the
  // TS side verifies the CONTRACT those outputs exist for — the pinned wire
  // payload must pass findLostHuman against the stored state (else the bot
  // POST would 422). This is the client/server seam tested end to end.
  for (const c of byFn("finalize")) {
    it(title(c), () => {
      const out = materialize(c.expect.out as AnnRecord[]);
      expect(findLostHuman(c.existing!, out)).toEqual(c.expect.lost_human_after);
      expect(c.expect.lost_human_after).toEqual([]); // the invariant itself
    });
  }
});

describe("parity fixture hygiene", () => {
  it("every case has a unique name and a recognized fn", () => {
    const fns = new Set([
      "anchor_sig",
      "sig_equal",
      "deep_equal",
      "find_match",
      "lost_human",
      "stamp_provenance",
      "finalize",
      "preserve_human",
    ]);
    const names = new Set<string>();
    for (const c of fixture.cases) {
      expect(fns.has(c.fn), `unknown fn ${c.fn} in ${c.name}`).toBe(true);
      expect(names.has(c.name), `duplicate case name ${c.name}`).toBe(false);
      names.add(c.name);
    }
  });

  it("every semantic divergence is flagged with a known_divergence note", () => {
    // expect.sig is language-scoped on every case (py json.dumps formatting vs
    // ts JSON.stringify — documented once in _doc, sig strings never cross
    // languages). The SEMANTIC expectations (equality booleans) and pinned
    // Python crashes are the real divergences and must each carry a note.
    for (const c of fixture.cases) {
      const semanticKeys = ["sig_equal", "deep_equal"];
      const scoped = semanticKeys.some((k) => {
        const v = c.expect[k];
        if (v === null || typeof v !== "object" || Array.isArray(v)) return false;
        const o = v as Record<string, unknown>;
        return "py" in o && "ts" in o && o.py !== o.ts;
      });
      const crashes = "py_raises" in c.expect;
      if (scoped || crashes) {
        expect(c.known_divergence, `${c.name} diverges but carries no known_divergence note`).toBeTruthy();
      }
    }
  });
});
